DROP DATABASE IF EXISTS CS401Project;
CREATE DATABASE CS401Project;
USE CS401Project;

CREATE TABLE Info (
  infoID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  accessType VARCHAR(45) NOT NULL,
  level INT NOT NULL,
  description VARCHAR(1024) NULL
);
